name: {{name}}
version: {{version}}
author: APN-Pucky
main: de.neuwirthinformatik.Alexander.bukkit.AUP.AUP
website: github.com/APN-Pucky/AutoUpdatePlugin
commands:
    helloworld:
        description: Hello World.
        aliases: [hw]
        usage: /helloworld